-- MySQL Script generated by MySQL Workbench
-- Sat Nov  8 16:06:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema delifhery
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema delifhery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `delifhery` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `delifhery` ;

-- -----------------------------------------------------
-- Table `delifhery`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delifhery`.`country` (
  `country_code` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`country_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delifhery`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delifhery`.`city` (
  `city_code` INT NOT NULL,
  `country_country_code` INT NOT NULL,
  `postal_code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`city_code`, `country_country_code`),
  INDEX `fk_city_country1_idx` (`country_country_code` ASC) VISIBLE,
  CONSTRAINT `fk_city_country1`
    FOREIGN KEY (`country_country_code`)
    REFERENCES `delifhery`.`country` (`country_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delifhery`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delifhery`.`address` (
  `street` VARCHAR(45) NOT NULL,
  `houseNo` INT NOT NULL,
  `id` INT NOT NULL,
  `city_city_code` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_address_city1_idx` (`city_city_code` ASC) VISIBLE,
  CONSTRAINT `fk_address_city1`
    FOREIGN KEY (`city_city_code`)
    REFERENCES `delifhery`.`city` (`city_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delifhery`.`participant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delifhery`.`participant` (
  `id` INT NOT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_participant_address1_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_participant_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `delifhery`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delifhery`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delifhery`.`customer` (
  `participant_id` INT NOT NULL,
  `authId` INT NULL,
  `username` VARCHAR(45) NOT NULL,
  INDEX `fk_customer_sender_idx` (`participant_id` ASC) VISIBLE,
  PRIMARY KEY (`participant_id`),
  UNIQUE INDEX `sender_id_UNIQUE` (`participant_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_sender`
    FOREIGN KEY (`participant_id`)
    REFERENCES `delifhery`.`participant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delifhery`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delifhery`.`email` (
  `eamail_address` VARCHAR(50) NOT NULL,
  `customer_participant_id` INT NOT NULL,
  UNIQUE INDEX `eamail_address_UNIQUE` (`eamail_address` ASC) VISIBLE,
  PRIMARY KEY (`customer_participant_id`, `eamail_address`),
  CONSTRAINT `fk_email_customer1`
    FOREIGN KEY (`customer_participant_id`)
    REFERENCES `delifhery`.`customer` (`participant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delifhery`.`PhoneNr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delifhery`.`PhoneNr` (
  `phone_nr` VARCHAR(50) NOT NULL,
  `customer_participant_id` INT NOT NULL,
  UNIQUE INDEX `phone_nr_UNIQUE` (`phone_nr` ASC) VISIBLE,
  PRIMARY KEY (`customer_participant_id`, `phone_nr`),
  CONSTRAINT `fk_PhoneNr_customer1`
    FOREIGN KEY (`customer_participant_id`)
    REFERENCES `delifhery`.`customer` (`participant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delifhery`.`payment_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delifhery`.`payment_status` (
  `state` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`state`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delifhery`.`shipment_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delifhery`.`shipment_order` (
  `id` INT NOT NULL,
  `priceEur` FLOAT NULL,
  `created_at` DATETIME NULL,
  `participant_id_sender` INT NOT NULL,
  `participant_id_receiver` INT NOT NULL,
  `payment_status_state` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`, `participant_id_sender`, `participant_id_receiver`),
  INDEX `fk_shipment_order_participant1_idx` (`participant_id_sender` ASC) VISIBLE,
  INDEX `fk_shipment_order_participant2_idx` (`participant_id_receiver` ASC) VISIBLE,
  INDEX `fk_shipment_order_payment_status1_idx` (`payment_status_state` ASC) VISIBLE,
  CONSTRAINT `fk_shipment_order_participant1`
    FOREIGN KEY (`participant_id_sender`)
    REFERENCES `delifhery`.`participant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shipment_order_participant2`
    FOREIGN KEY (`participant_id_receiver`)
    REFERENCES `delifhery`.`participant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shipment_order_payment_status1`
    FOREIGN KEY (`payment_status_state`)
    REFERENCES `delifhery`.`payment_status` (`state`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delifhery`.`package`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delifhery`.`package` (
  `id` INT NOT NULL,
  `weightKg` FLOAT NULL,
  `lengthCm` FLOAT NULL,
  `widthCm` FLOAT NULL,
  `heightCm` FLOAT NULL,
  `tracking_history_id` INT NOT NULL,
  `shipment_order_id` INT NOT NULL,
  PRIMARY KEY (`id`, `shipment_order_id`),
  INDEX `fk_package_shipment_order1_idx` (`shipment_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_package_shipment_order1`
    FOREIGN KEY (`shipment_order_id`)
    REFERENCES `delifhery`.`shipment_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delifhery`.`postOffice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delifhery`.`postOffice` (
  `name` VARCHAR(45) NOT NULL,
  `participant_id` INT NOT NULL,
  PRIMARY KEY (`participant_id`),
  CONSTRAINT `fk_postOffice_sender1`
    FOREIGN KEY (`participant_id`)
    REFERENCES `delifhery`.`participant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delifhery`.`tracking_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delifhery`.`tracking_history` (
  `id` INT NOT NULL,
  `package_id` INT NOT NULL,
  `shipment_order_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tracking_history_package1_idx` (`package_id` ASC, `shipment_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_tracking_history_package1`
    FOREIGN KEY (`package_id` , `shipment_order_id`)
    REFERENCES `delifhery`.`package` (`id` , `shipment_order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delifhery`.`tracking_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delifhery`.`tracking_status` (
  `status` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delifhery`.`track_entry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delifhery`.`track_entry` (
  `updated_at` DATETIME NULL,
  `id` INT NOT NULL,
  `postOffice_sender_id` INT NOT NULL,
  `additional_infomation` VARCHAR(200) NULL,
  `tracking_status_status` VARCHAR(50) NOT NULL,
  `tracking_history_id` INT NOT NULL,
  PRIMARY KEY (`id`, `postOffice_sender_id`, `tracking_history_id`),
  INDEX `fk_track_entry_postOffice1_idx` (`postOffice_sender_id` ASC) VISIBLE,
  INDEX `fk_track_entry_tracking_status1_idx` (`tracking_status_status` ASC) VISIBLE,
  INDEX `fk_track_entry_tracking_history1_idx` (`tracking_history_id` ASC) VISIBLE,
  CONSTRAINT `fk_track_entry_postOffice1`
    FOREIGN KEY (`postOffice_sender_id`)
    REFERENCES `delifhery`.`postOffice` (`participant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_track_entry_tracking_status1`
    FOREIGN KEY (`tracking_status_status`)
    REFERENCES `delifhery`.`tracking_status` (`status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_track_entry_tracking_history1`
    FOREIGN KEY (`tracking_history_id`)
    REFERENCES `delifhery`.`tracking_history` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `delifhery`.`subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `delifhery`.`subscription` (
  `id` INT NOT NULL,
  `is_active` TINYINT NULL,
  `tracking_history_id` INT NOT NULL,
  `customer_participant_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tracking_history_id`, `customer_participant_id`),
  INDEX `fk_subscription_tracking_history1_idx` (`tracking_history_id` ASC) VISIBLE,
  INDEX `fk_subscription_customer1_idx` (`customer_participant_id` ASC) VISIBLE,
  CONSTRAINT `fk_subscription_tracking_history1`
    FOREIGN KEY (`tracking_history_id`)
    REFERENCES `delifhery`.`tracking_history` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subscription_customer1`
    FOREIGN KEY (`customer_participant_id`)
    REFERENCES `delifhery`.`customer` (`participant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
