
ALTER USER '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_USER_PW}' WITH MAX_USER_CONNECTIONS 20;


CREATE USER IF NOT EXISTS '${DB_USER}'@'%' IDENTIFIED BY '${DB_USER_PW}';

GRANT ALL PRIVILEGES ON delifhery.* TO '${DB_USER}'@'localhost';
GRANT ALL PRIVILEGES ON delifhery.* TO '${DB_USER}'@'%';

FLUSH PRIVILEGES;
