name: Self-Hosted Runner Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run test command
        run: echo "Runner sucessfully connected and executes Workflows !"
